version: '3.8'
services:
  app:
    build: .
    depends_on:
      - database
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
  
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - 5432:5432
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql